
CREATE TABLE commodities (
	id VARCHAR(255) NOT NULL,
	nombre VARCHAR(255) NULL,
	tipo VARCHAR(50) NOT NULL,
	CONSTRAINT commodities_pk PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
