name: ed-colonizacion

services:
    ed-colonizacion-api:
        container_name: ed-colonizacion-api
        # image: node:21-alpine
        image: node-express-ed
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./assets:/usr/src/app/assets
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5000:5000
        restart: unless-stopped
        logging:
            options:
                max-size: "10m"
                max-file: "3"

        # Opcional: Límite estricto de seguridad para que jamás consuma más de 128MB de RAM en el VPS
        deploy:
            resources:
                limits:
                    memory: 192M

networks:
    default:
        name: proxylan
