name: ed-colonizacion

services:
    ed-colonizacion-api:
        container_name: ed-colonizacion-api
        # image: node:21-alpine
        image: node-express-ed
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./assets:/usr/src/app/assets
        ports:
            - 5000:5000
        restart: unless-stopped
        logging:
            options:
                max-size: "10m"
                max-file: "3"

networks:
    default:
        name: proxylan
